/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.text.DateFormat;
import java.util.Date;
import model.Usuario;

/**
 *
 * @author onerb
 */
public class JFPrincipal extends javax.swing.JFrame {
    private Usuario obj;
    /**
     * Creates new form JFPrincipal
     */
    public JFPrincipal() {
        initComponents();
    }
    public JFPrincipal(Usuario obj) {
        this();
        this.obj = obj;
        jLabel1.setText("Usuário: "+obj.getUsuario());
//        jLabel2.setText("Função: "+obj.getTipo());
        if(obj.getTipo()==1)
            jLabel2.setText("Função: Administrador");
        jbusuarios.setEnabled(true);
        jbcaminhao.setEnabled(true);
        jbrelatorio.setEnabled(true);
        jbpecas.setEnabled(true);
        if(obj.getTipo()==2)
            jLabel2.setText("Função: Motorista");
        acessosres();
//        if(obj.getTipo()==1)
//            jButton1.setEnabled(true);
//        else
//            jButton1.setEnabled(false);

    }
    public boolean acessosres(){
        while(obj.getTipo()==2){
            jbusuarios.setEnabled(false);
            jbpecas.setEnabled(false);
         return true;
}
        return true;
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlEmpresa = new javax.swing.JLabel();
        jbusuarios = new javax.swing.JButton();
        jbpecas = new javax.swing.JButton();
        jbrelatorio = new javax.swing.JButton();
        jbcaminhao = new javax.swing.JButton();
        jdpareatrabalho = new javax.swing.JDesktopPane();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jldata = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jlEmpresa.setFont(new java.awt.Font("Times New Roman", 1, 55)); // NOI18N
        jlEmpresa.setText("BTA Transportes");
        getContentPane().add(jlEmpresa, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 0, 586, -1));

        jbusuarios.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jbusuarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/User.png"))); // NOI18N
        jbusuarios.setText("Usuários");
        jbusuarios.setToolTipText("Usuários");
        jbusuarios.setContentAreaFilled(false);
        jbusuarios.setEnabled(false);
        jbusuarios.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jbusuarios.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbusuarios.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jbusuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbusuariosActionPerformed(evt);
            }
        });
        getContentPane().add(jbusuarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, 100, -1));

        jbpecas.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jbpecas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/Pecas.png"))); // NOI18N
        jbpecas.setText("Peças");
        jbpecas.setToolTipText("Peças");
        jbpecas.setContentAreaFilled(false);
        jbpecas.setEnabled(false);
        jbpecas.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbpecas.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jbpecas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbpecasActionPerformed(evt);
            }
        });
        getContentPane().add(jbpecas, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 270, 100, -1));

        jbrelatorio.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jbrelatorio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/Relatorio.png"))); // NOI18N
        jbrelatorio.setText("Relatórios");
        jbrelatorio.setToolTipText("Relatórios");
        jbrelatorio.setContentAreaFilled(false);
        jbrelatorio.setEnabled(false);
        jbrelatorio.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbrelatorio.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jbrelatorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbrelatorioActionPerformed(evt);
            }
        });
        getContentPane().add(jbrelatorio, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 380, 100, -1));

        jbcaminhao.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jbcaminhao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/Caminhao.png"))); // NOI18N
        jbcaminhao.setText("Caminhões");
        jbcaminhao.setToolTipText("Cminhões");
        jbcaminhao.setContentAreaFilled(false);
        jbcaminhao.setEnabled(false);
        jbcaminhao.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbcaminhao.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jbcaminhao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbcaminhaoActionPerformed(evt);
            }
        });
        getContentPane().add(jbcaminhao, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 490, 110, 83));

        jdpareatrabalho.setAutoscrolls(true);

        javax.swing.GroupLayout jdpareatrabalhoLayout = new javax.swing.GroupLayout(jdpareatrabalho);
        jdpareatrabalho.setLayout(jdpareatrabalhoLayout);
        jdpareatrabalhoLayout.setHorizontalGroup(
            jdpareatrabalhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 830, Short.MAX_VALUE)
        );
        jdpareatrabalhoLayout.setVerticalGroup(
            jdpareatrabalhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 520, Short.MAX_VALUE)
        );

        getContentPane().add(jdpareatrabalho, new org.netbeans.lib.awtextra.AbsoluteConstraints(101, 74, 830, 520));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setText("Usuário:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 610, -1, 24));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel2.setText("Função:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 610, -1, 24));

        jldata.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jldata.setText("Data");
        getContentPane().add(jldata, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 610, -1, -1));

        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/login.png"))); // NOI18N
        jButton1.setText("Login");
        jButton1.setContentAreaFilled(false);
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbusuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbusuariosActionPerformed

        JIFUsuarios janela = new JIFUsuarios();
        jdpareatrabalho.add(janela);
        janela.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_jbusuariosActionPerformed

    private void jbrelatorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbrelatorioActionPerformed
        JIFRelatorio janela = new JIFRelatorio();
        jdpareatrabalho.add(janela);
        janela.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_jbrelatorioActionPerformed

    private void jbpecasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbpecasActionPerformed
        JIFPecas janela = new JIFPecas();
        jdpareatrabalho.add(janela);
        janela.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_jbpecasActionPerformed

    private void jbcaminhaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbcaminhaoActionPerformed
        JIFCaminhoes janela = new JIFCaminhoes();
        jdpareatrabalho.add(janela);
        janela.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_jbcaminhaoActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        Date data = new Date(); 
        DateFormat formatador = DateFormat.getDateInstance(DateFormat.SHORT);
        jldata.setText(formatador.format(data));
//        jlhora.setText(formatador.format(data));
    }//GEN-LAST:event_formWindowActivated

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
     new JFLogin().setVisible(true);
     dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
                new JFPrincipal().setVisible(true);
                
          }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton jbcaminhao;
    private javax.swing.JButton jbpecas;
    private javax.swing.JButton jbrelatorio;
    private javax.swing.JButton jbusuarios;
    private javax.swing.JDesktopPane jdpareatrabalho;
    private javax.swing.JLabel jlEmpresa;
    private javax.swing.JLabel jldata;
    // End of variables declaration//GEN-END:variables
}
