/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import data.CaminhaoData;
import extras.tratarFormularios;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Caminhao;

/**
 *
 * @author onerb
 */
public class JIFCaminhoes extends javax.swing.JInternalFrame {
    private Caminhao obj;
    private CaminhaoData DAO;
    private ArrayList<Caminhao> listadecaminhoes;
    private int acao;
    /**
     * Creates new form JIFCaminhoes
     */
    public JIFCaminhoes() {
        try {
           obj = new Caminhao();
           DAO = new CaminhaoData();
           listadecaminhoes = new ArrayList<>();
           acao=0;
        initComponents();
        } catch (Exception erro) {
            JOptionPane.showMessageDialog(null, erro.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jlidcaminhao = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jtfPlaca = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jtfChassi = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jbNovo = new javax.swing.JButton();
        jbEditar = new javax.swing.JButton();
        jbCancelar = new javax.swing.JButton();
        jbSalvar = new javax.swing.JButton();
        jtfPesquisar = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtbCaminhoes = new javax.swing.JTable();
        jbexcluir = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtfModelo = new javax.swing.JTextArea();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("CAMINHÕES");

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jLabel1.setText("ID");

        jlidcaminhao.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jlidcaminhao.setText("0");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jLabel3.setText("Placa:");

        jtfPlaca.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jtfPlaca.setEnabled(false);

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jLabel4.setText("Chassi:");

        jtfChassi.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jtfChassi.setEnabled(false);

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jLabel5.setText("Modelo: ");

        jbNovo.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jbNovo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/Add.png"))); // NOI18N
        jbNovo.setText("Novo");
        jbNovo.setContentAreaFilled(false);
        jbNovo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbNovo.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jbNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbNovoActionPerformed(evt);
            }
        });

        jbEditar.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jbEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/Editar.png"))); // NOI18N
        jbEditar.setText("Editar");
        jbEditar.setContentAreaFilled(false);
        jbEditar.setEnabled(false);
        jbEditar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbEditar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jbEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbEditarActionPerformed(evt);
            }
        });

        jbCancelar.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jbCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/Cancel.png"))); // NOI18N
        jbCancelar.setText("Cancelar");
        jbCancelar.setContentAreaFilled(false);
        jbCancelar.setEnabled(false);
        jbCancelar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbCancelar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jbCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCancelarActionPerformed(evt);
            }
        });

        jbSalvar.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jbSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/Salvar.png"))); // NOI18N
        jbSalvar.setText("Salvar");
        jbSalvar.setContentAreaFilled(false);
        jbSalvar.setEnabled(false);
        jbSalvar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbSalvar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jbSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSalvarActionPerformed(evt);
            }
        });

        jtfPesquisar.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jtfPesquisar.setText("Digite um modelo...");
        jtfPesquisar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtfPesquisarMouseClicked(evt);
            }
        });
        jtfPesquisar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtfPesquisarKeyReleased(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jLabel6.setText("Pesquisar: ");

        jtbCaminhoes.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jtbCaminhoes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "Placa", "Modelo", "Chassi"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jtbCaminhoes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtbCaminhoesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jtbCaminhoes);

        jbexcluir.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jbexcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/Delete.png"))); // NOI18N
        jbexcluir.setText("Excluir");
        jbexcluir.setContentAreaFilled(false);
        jbexcluir.setEnabled(false);
        jbexcluir.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbexcluir.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jbexcluir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbexcluirMouseClicked(evt);
            }
        });
        jbexcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbexcluirActionPerformed(evt);
            }
        });

        jtfModelo.setColumns(20);
        jtfModelo.setRows(5);
        jtfModelo.setEnabled(false);
        jScrollPane2.setViewportView(jtfModelo);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(22, 22, 22)
                                .addComponent(jScrollPane2))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtfPesquisar))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 667, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jlidcaminhao, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel3))
                                .addGap(33, 33, 33)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jtfPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jtfChassi, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(jbNovo)
                        .addGap(55, 55, 55)
                        .addComponent(jbEditar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jbCancelar)
                        .addGap(52, 52, 52)
                        .addComponent(jbSalvar)
                        .addGap(44, 44, 44)
                        .addComponent(jbexcluir)
                        .addGap(63, 63, 63))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jlidcaminhao))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtfPlaca, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jtfChassi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel5)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbNovo)
                    .addComponent(jbEditar)
                    .addComponent(jbCancelar)
                    .addComponent(jbSalvar)
                    .addComponent(jbexcluir))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbNovoActionPerformed
    jtfPlaca.setEnabled(true);
    jtfChassi.setEnabled(true);
    jtfModelo.setEnabled(true);
    jbCancelar.setEnabled(true);
    jbSalvar.setEnabled(true);
    jtfModelo.setEditable(true);
    jtfChassi.setText("");
    jtfModelo.setText("");
    jtfPlaca.setText("");
    acao = 1;

        // TODO add your handling code here:
    }//GEN-LAST:event_jbNovoActionPerformed

    private void jbCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCancelarActionPerformed
          
        jtfPlaca.setEnabled(false);
        jtfChassi.setEnabled(false);
        jtfModelo.setEnabled(false);
        jbCancelar.setEnabled(false);
        jbSalvar.setEnabled(false);
        jtfPlaca.setText("");
        jtfChassi.setText("");
        jtfModelo.setText("");
        jtfModelo.setEnabled(false);
        jLabel6.setEnabled(true);
        jtfPesquisar.setEnabled(true);
        jbNovo.setEnabled(true);
        jtbCaminhoes.setEnabled(true);
        jlidcaminhao.setText("");
        jtfPesquisar.setText("");
        jbexcluir.setEnabled(false);
    }//GEN-LAST:event_jbCancelarActionPerformed

    private void jbSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSalvarActionPerformed

        if(validarCampos()){
              if(preencherObjeto()){
                  if(acao==1){
                  try {
                      if(DAO.incluir(obj)){
                          JOptionPane.showMessageDialog(this, "Salvo com sucesso!", "Meu Sistema", JOptionPane.INFORMATION_MESSAGE);
                          jbCancelarActionPerformed(evt);
                      } else{
                          JOptionPane.showMessageDialog(this, "Não Salvou!");
                      }
                  } catch (Exception ex) {
                      Logger.getLogger(JIFUsuarios.class.getName()).log(Level.SEVERE, null, ex);
                  }
                  }
                  if(acao==2){
                  try {
                      if(DAO.editar(obj)){
                          JOptionPane.showMessageDialog(this, "Atualizado com sucesso!", "Meu Sistema", JOptionPane.INFORMATION_MESSAGE);
                          jbCancelarActionPerformed(evt);
                      } else{
                          JOptionPane.showMessageDialog(this, "Não Atualizou!");
                      }
                  } catch (Exception ex) {
                      Logger.getLogger(JIFUsuarios.class.getName()).log(Level.SEVERE, null, ex);
                  }
                  }
         }
    
  }
        // TODO add your handling code here:
    }//GEN-LAST:event_jbSalvarActionPerformed

    private void jtfPesquisarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfPesquisarKeyReleased
        try {DefaultTableModel mp = (DefaultTableModel) jtbCaminhoes.getModel();
            mp.setNumRows(0);
            if(jtfPesquisar.getText().length()>=0){
                listadecaminhoes=DAO.Pesquisar(jtfPesquisar.getText());
                for(Caminhao c: listadecaminhoes){
                    mp.addRow(new String[]{""+c.getId(),c.getPlaca(),c.getModelo(),c.getChassi()});
                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Erro:"+e.getMessage(),"Erro ao pesquisar",JOptionPane.ERROR_MESSAGE);
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_jtfPesquisarKeyReleased

    private void jtbCaminhoesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtbCaminhoesMouseClicked
    try {
            int linhaSelecionada = jtbCaminhoes.getSelectedRow();
            if(linhaSelecionada>-1){
                jlidcaminhao.setText(""+listadecaminhoes.get(linhaSelecionada).getId());
                jtfPlaca.setText(""+listadecaminhoes.get(linhaSelecionada).getPlaca());
                jtfChassi.setText(listadecaminhoes.get(linhaSelecionada).getChassi());
                jtfModelo.setText(listadecaminhoes.get(linhaSelecionada).getModelo());
                jbEditar.setEnabled(true);
                jbexcluir.setEnabled(true);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Erro:"+e.getMessage(),"Erro ao pesquisar",JOptionPane.ERROR_MESSAGE);
        }     


        // TODO add your handling code here:
    }//GEN-LAST:event_jtbCaminhoesMouseClicked

    private void jbEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbEditarActionPerformed
    try {
            tratarFormularios.habilitarCampos(this);
                    } catch (Exception ex) {
            Logger.getLogger(JIFUsuarios.class.getName()).log(Level.SEVERE, null, ex);
        }
       jbNovo.setEnabled(false);
       jtfModelo.setEnabled(true);
       acao = 2;

        // TODO add your handling code here:
    }//GEN-LAST:event_jbEditarActionPerformed

    private void jbexcluirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbexcluirMouseClicked
        
        // TODO add your handling code here:
    }//GEN-LAST:event_jbexcluirMouseClicked

    private void jbexcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbexcluirActionPerformed
        try {
            if (DAO.excluir(Integer.parseInt(jlidcaminhao.getText()))) {
                JOptionPane.showMessageDialog(this, "Excluído com sucesso!", "Meu sistema", JOptionPane.INFORMATION_MESSAGE);
                jbEditar.setEnabled(false);
                jbexcluir.setEnabled(false);
                jtfModelo.setText("");
                jtfModelo.setEnabled(false);
                tratarFormularios.limparCampos(this);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Erro: " + e.getMessage());
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jbexcluirActionPerformed

    private void jtfPesquisarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtfPesquisarMouseClicked
        jtfPesquisar.setText("");
    }//GEN-LAST:event_jtfPesquisarMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton jbCancelar;
    private javax.swing.JButton jbEditar;
    private javax.swing.JButton jbNovo;
    private javax.swing.JButton jbSalvar;
    private javax.swing.JButton jbexcluir;
    private javax.swing.JLabel jlidcaminhao;
    private javax.swing.JTable jtbCaminhoes;
    private javax.swing.JTextField jtfChassi;
    private javax.swing.JTextArea jtfModelo;
    private javax.swing.JTextField jtfPesquisar;
    private javax.swing.JTextField jtfPlaca;
    // End of variables declaration//GEN-END:variables

private boolean validarCampos(){
    String msg = "";
    if(jtfPlaca.getText().length()<8)
        msg+="\nDigite uma placa válida!";
    if(jtfPlaca.getText().length()>8)
        msg+="\nDigite uma placa válida!"; 
    if(jtfModelo.getText().length()==0)
        msg+="\nDigite o modelo do veículo!";
    if(jtfChassi.getText().length()==0)
        msg+="\nDigite o numero do chassi!";
    if(jtfChassi.getText().length()>17)
        msg+="\nNumero de chassis Inválido!";
    if(msg.length()==0)
       return true;
    else{
       JOptionPane.showMessageDialog(this, "Corrija os seguintes campos" + msg, "Meu sistema", JOptionPane.ERROR_MESSAGE);
       return false;
    }
}
private boolean preencherObjeto(){
    obj.setId(Integer.parseInt(jlidcaminhao.getText()));
    obj.setPlaca(jtfPlaca.getText());
    obj.setModelo(jtfModelo.getText());
    obj.setChassi(jtfChassi.getText());
    return true;
}
}