/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import data.PecasData;
import extras.tratarFormularios;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Pecas;

/**
 *
 * @author onerb
 */
public class JIFPecas extends javax.swing.JInternalFrame {
    private Pecas obj;
    private PecasData DAO;
    private ArrayList<Pecas> listadePecas;
    private int acao;
    /**
     * Creates new form JIFProdutos
     */
    public JIFPecas() {
        try {
           obj = new Pecas();
           DAO = new PecasData();
           listadePecas = new ArrayList<>();
           acao=0;
        initComponents();
        } catch (Exception erro) {
            JOptionPane.showMessageDialog(null, erro.getMessage());
        }
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jtfprecocusto = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jtfprecovenda = new javax.swing.JTextField();
        jbnovopeca = new javax.swing.JButton();
        jbcancelarpeca = new javax.swing.JButton();
        jbsalvarpeca = new javax.swing.JButton();
        jlIdprod = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtfdescricao = new javax.swing.JTextArea();
        jLabel7 = new javax.swing.JLabel();
        jtfPesquisar = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtbpecas = new javax.swing.JTable();
        jbexcluir = new javax.swing.JButton();
        jbeditar = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Cadastro de Peça");
        try {
            setSelected(true);
        } catch (java.beans.PropertyVetoException e1) {
            e1.printStackTrace();
        }

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jLabel1.setText("ID");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jLabel2.setText("Descrição / Modelo / Marca");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jLabel3.setText("Preço de custo");

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jLabel4.setText("R$");

        jtfprecocusto.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jtfprecocusto.setEnabled(false);

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jLabel5.setText("Preço de Venda");

        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jLabel6.setText("R$");

        jtfprecovenda.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jtfprecovenda.setEnabled(false);

        jbnovopeca.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jbnovopeca.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/Add.png"))); // NOI18N
        jbnovopeca.setText("Novo");
        jbnovopeca.setToolTipText("Novo");
        jbnovopeca.setContentAreaFilled(false);
        jbnovopeca.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbnovopeca.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jbnovopeca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbnovopecaActionPerformed(evt);
            }
        });

        jbcancelarpeca.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jbcancelarpeca.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/Cancel.png"))); // NOI18N
        jbcancelarpeca.setText("Cancelar");
        jbcancelarpeca.setToolTipText("Cancelar");
        jbcancelarpeca.setContentAreaFilled(false);
        jbcancelarpeca.setEnabled(false);
        jbcancelarpeca.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbcancelarpeca.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jbcancelarpeca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbcancelarpecaActionPerformed(evt);
            }
        });

        jbsalvarpeca.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jbsalvarpeca.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/Salvar.png"))); // NOI18N
        jbsalvarpeca.setText("Salvar");
        jbsalvarpeca.setToolTipText("Salvar");
        jbsalvarpeca.setContentAreaFilled(false);
        jbsalvarpeca.setEnabled(false);
        jbsalvarpeca.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbsalvarpeca.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jbsalvarpeca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbsalvarpecaActionPerformed(evt);
            }
        });

        jlIdprod.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jlIdprod.setText("0");

        jtfdescricao.setColumns(20);
        jtfdescricao.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jtfdescricao.setRows(5);
        jtfdescricao.setEnabled(false);
        jScrollPane1.setViewportView(jtfdescricao);

        jLabel7.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jLabel7.setText("Pesquisar: ");

        jtfPesquisar.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jtfPesquisar.setText("Digite uma descrição...");
        jtfPesquisar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtfPesquisarMouseClicked(evt);
            }
        });
        jtfPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfPesquisarActionPerformed(evt);
            }
        });
        jtfPesquisar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtfPesquisarKeyReleased(evt);
            }
        });

        jtbpecas.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jtbpecas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Id", "Descrição", "Custo", "Venda"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jtbpecas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtbpecasMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jtbpecas);

        jbexcluir.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jbexcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/Delete.png"))); // NOI18N
        jbexcluir.setText("Excluir");
        jbexcluir.setToolTipText("Excluir");
        jbexcluir.setContentAreaFilled(false);
        jbexcluir.setEnabled(false);
        jbexcluir.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbexcluir.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jbexcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbexcluirActionPerformed(evt);
            }
        });

        jbeditar.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jbeditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/Editar.png"))); // NOI18N
        jbeditar.setText("Editar");
        jbeditar.setToolTipText("Editar");
        jbeditar.setContentAreaFilled(false);
        jbeditar.setEnabled(false);
        jbeditar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbeditar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jbeditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbeditarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtfPesquisar))
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addComponent(jbnovopeca, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(3, 3, 3)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(63, 63, 63)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel6)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jbcancelarpeca)
                                                .addGap(53, 53, 53)
                                                .addComponent(jbeditar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(10, 10, 10)))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(36, 36, 36)
                                                .addComponent(jbexcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(jbsalvarpeca, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(18, 18, 18)
                                                .addComponent(jtfprecovenda, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel4)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jtfprecocusto, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(50, 50, 50)
                                                .addComponent(jLabel3)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel5)
                                        .addGap(135, 135, 135))))
                            .addComponent(jLabel2)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(jlIdprod)))
                        .addGap(0, 30, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jlIdprod))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jtfPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(11, 11, 11)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfprecocusto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jtfprecovenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jbexcluir, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbeditar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbnovopeca, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbcancelarpeca, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbsalvarpeca))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbnovopecaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbnovopecaActionPerformed
        jtfdescricao.setEnabled(true);
        jtfprecocusto.setEnabled(true);
        jtfprecovenda.setEnabled(true);
        jbcancelarpeca.setEnabled(true);
        jbsalvarpeca.setEnabled(true);
        acao = 1;
        // TODO add your handling code here:
    }//GEN-LAST:event_jbnovopecaActionPerformed

    private void jbsalvarpecaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbsalvarpecaActionPerformed
        if(validarCampos()){
            if(preencherObjeto()){
                if(acao==1){
                    try {
                        if(DAO.incluir(obj)){
                         JOptionPane.showMessageDialog(this, "Salvo com sucesso!", "Meu Sistema", JOptionPane.INFORMATION_MESSAGE);
                            jbcancelarpecaActionPerformed(evt);
                        }else{
                         JOptionPane.showMessageDialog(this, "Não Salvou!"); 
                        }
                    } catch (Exception ex) {
                        Logger.getLogger(JIFPecas.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
                if(acao==2){
                    try {
                        if(DAO.editar(obj)){
                         JOptionPane.showMessageDialog(this, "Atualizado com sucesso!", "Meu Sistema", JOptionPane.INFORMATION_MESSAGE);   
                            jbcancelarpecaActionPerformed(evt);
                        }else{
                         JOptionPane.showMessageDialog(this, "Não Salvou!");   
                        }
                    } catch (Exception ex) {
                        Logger.getLogger(JIFPecas.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
            }
        }

//       if(validarCampos()){
//              if(preencherObjeto()){
//                  if(acao==1){
//                  try {
//                      if(DAO.incluir(obj)){
//                          JOptionPane.showMessageDialog(this, "Salvo com sucesso!", "Meu Sistema", JOptionPane.INFORMATION_MESSAGE);
//                          jbcancelarpecaActionPerformed(evt);
//                      } else{
//                          JOptionPane.showMessageDialog(this, "Não Salvou!");
//                      }
//                  } catch (Exception ex) {
//                      Logger.getLogger(JIFUsuarios.class.getName()).log(Level.SEVERE, null, ex);
//                  }
//                  }
//                  if(acao==2){
//                  try {
//                      if(DAO.editar(obj)){
//                          JOptionPane.showMessageDialog(this, "Atualizado com sucesso!", "Meu Sistema", JOptionPane.INFORMATION_MESSAGE);
//                          jbcancelarpecaActionPerformed(evt);
//                      } else{
//                          JOptionPane.showMessageDialog(this, "Não Atualizou!");
//                      }
//                  } catch (Exception ex) {
//                      Logger.getLogger(JIFUsuarios.class.getName()).log(Level.SEVERE, null, ex);
//                  }
//                  }
//         }
//    } 
    }//GEN-LAST:event_jbsalvarpecaActionPerformed

    private void jbcancelarpecaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbcancelarpecaActionPerformed
        jtfdescricao.setEnabled(false);
        jtfprecocusto.setEnabled(false);
        jtfprecovenda.setEnabled(false);
        jbcancelarpeca.setEnabled(false);
        jbsalvarpeca.setEnabled(false);
        jtfdescricao.setText("");
        jtfprecocusto.setText("");
        jtfprecovenda.setText("");
        jbexcluir.setEnabled(false);
        jlIdprod.setText("");
        jbnovopeca.setEnabled(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_jbcancelarpecaActionPerformed

    private void jtfPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfPesquisarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfPesquisarActionPerformed

    private void jtfPesquisarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfPesquisarKeyReleased
        try {DefaultTableModel mp = (DefaultTableModel) jtbpecas.getModel();
            mp.setNumRows(0);
            if(jtfPesquisar.getText().length()>=0){
                listadePecas=DAO.Pesquisar(jtfPesquisar.getText());
                for(Pecas p: listadePecas){
                    mp.addRow(new String[]{""+p.getId(),p.getDescricao(),""+p.getCusto(),""+p.getPreco_venda()});
                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Erro:"+e.getMessage(),"Erro ao pesquisar",JOptionPane.ERROR_MESSAGE);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfPesquisarKeyReleased

    private void jtbpecasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtbpecasMouseClicked
         try {
            int linhaSelecionada = jtbpecas.getSelectedRow();
            if(linhaSelecionada>-1){
                jlIdprod.setText(""+listadePecas.get(linhaSelecionada).getId());
                jtfdescricao.setText(listadePecas.get(linhaSelecionada).getDescricao());
                jtfprecocusto.setText(""+listadePecas.get(linhaSelecionada).getCusto());
                jtfprecovenda.setText(""+listadePecas.get(linhaSelecionada).getPreco_venda());
                jbexcluir.setEnabled(true);
                jbsalvarpeca.setEnabled(false);
                jbeditar.setEnabled(true);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Erro:"+e.getMessage(),"Erro ao pesquisar",JOptionPane.ERROR_MESSAGE);
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_jtbpecasMouseClicked

    private void jbeditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbeditarActionPerformed
        try {
            tratarFormularios.habilitarCampos(this);
        } catch (Exception ex) {
            Logger.getLogger(JIFPecas.class.getName()).log(Level.SEVERE, null, ex);
        }
        jbnovopeca.setEnabled(false);
        jtfdescricao.setEnabled(true);
        jbeditar.setEnabled(false);
        jbexcluir.setEnabled(false);
        jtfPesquisar.setText("");
        acao = 2;
    }//GEN-LAST:event_jbeditarActionPerformed

    private void jbexcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbexcluirActionPerformed
        try {
            if (DAO.excluir(Integer.parseInt(jlIdprod.getText()))) {
                JOptionPane.showMessageDialog(this, "Excluído com sucesso!", "Meu sistema", JOptionPane.INFORMATION_MESSAGE);
                jbeditar.setEnabled(false);
                jbexcluir.setEnabled(false);
                jtfPesquisar.setText("");
                jtfprecocusto.setText("");
                jtfprecovenda.setText("");
                jtfdescricao.setText("");
                jbnovopeca.setEnabled(true);
                jbcancelarpeca.setEnabled(false);
                jbsalvarpeca.setEnabled(false);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Erro: " + e.getMessage());
        }



        // TODO add your handling code here:
    }//GEN-LAST:event_jbexcluirActionPerformed

    private void jtfPesquisarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtfPesquisarMouseClicked
    jtfPesquisar.setText("");
    }//GEN-LAST:event_jtfPesquisarMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton jbcancelarpeca;
    private javax.swing.JButton jbeditar;
    private javax.swing.JButton jbexcluir;
    private javax.swing.JButton jbnovopeca;
    private javax.swing.JButton jbsalvarpeca;
    private javax.swing.JLabel jlIdprod;
    private javax.swing.JTable jtbpecas;
    private javax.swing.JTextField jtfPesquisar;
    private javax.swing.JTextArea jtfdescricao;
    private javax.swing.JTextField jtfprecocusto;
    private javax.swing.JTextField jtfprecovenda;
    // End of variables declaration//GEN-END:variables

private boolean preencherObjeto(){
    obj.setId(Integer.parseInt(jlIdprod.getText()));
    obj.setDescricao(jtfdescricao.getText());
    obj.setCusto(Float.parseFloat(jtfprecocusto.getText()));
    obj.setPreco_venda(Float.parseFloat(jtfprecovenda.getText()));
    ;
    
    return true;
}

private boolean validarCampos(){
    String msg = "";
    if(jtfdescricao.getText().length()<5)
        msg+="\nA descrição deve ter pelo menos 5 caracteres!";
    if(jtfdescricao.getText().length()>100)
        msg+="\nA descrição deve ter menos de 100 caracteres!"; 
    if(jtfprecocusto.getText().length()==0)
        msg+="\nDigite o preço de custo!";
    if(jtfprecovenda.getText().length()==0)
        msg+="\nDigite o valor de venda!";
    if(msg.length()==0)
       return true;
    else{
       JOptionPane.showMessageDialog(this, "Corrija os seguintes campos" + msg, "Meu sistema", JOptionPane.ERROR_MESSAGE);
       return false;
    }
}
}